services:
  backend:
    build: ./task-management-backend
    container_name: task-backend
    ports:
      - "8080:8080"
    networks:
      - task-net

  frontend:
    build: ./task-management-frontend
    container_name: task-frontend
    ports:
      - "4200:4200"
    networks:
      - task-net
    depends_on:
      - backend

networks:
  task-net:
    driver: bridge

